# Generated by Django 5.0.1 on 2024-09-30 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('adres', models.CharField(max_length=255)),
                ('numer_telefonu', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('kategoria', models.CharField(choices=[('nowy', 'Nowy'), ('staly', 'Stały'), ('VIP', 'VIP')], max_length=10)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaKontaktu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_kontaktu', models.DateTimeField(auto_now_add=True)),
                ('typ_kontaktu', models.CharField(choices=[('telefon', 'Telefon'), ('email', 'E-mail'), ('spotkanie', 'Spotkanie')], max_length=15)),
                ('notatka', models.TextField()),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.klient')),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zamowienia', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('w_realizacji', 'W realizacji'), ('zrealizowane', 'Zrealizowane'), ('anulowane', 'Anulowane')], max_length=15)),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.klient')),
            ],
        ),
    ]
