# Generated by Django 5.0.1 on 2024-09-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_produkt_zamowienie_produkty'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='opis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='nazwa',
            field=models.CharField(max_length=255),
        ),
    ]
