# Generated by Django 5.0.1 on 2024-10-07 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_produkt_opis_alter_produkt_nazwa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Powiadomienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=255)),
                ('data', models.DateTimeField()),
                ('opis', models.TextField(blank=True, null=True)),
                ('typ', models.CharField(choices=[('zadanie', 'Zadanie'), ('przypomnienie', 'Przypomnienie'), ('spotkanie', 'Spotkanie')], max_length=20)),
                ('klient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_app.klient')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
