# Generated by Django 5.0.1 on 2024-10-08 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_powiadomienie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zamowienie',
            name='produkty',
        ),
        migrations.CreateModel(
            name='ZamowienieProdukt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.PositiveIntegerField(default=1)),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.produkt')),
                ('zamowienie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.zamowienie')),
            ],
        ),
    ]
